monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        channels:
            - console
            - doctrine
            - debug_channel
            - event
            - profiler
            - router
            - http_client

        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels:
                    - '!console'
                    - '!doctrine'
                    - '!debug_channel'
                    - '!event'
                    - '!profiler'
                    - '!router'
                    - '!http_client'

            console:
                type: stream
                path: "%kernel.logs_dir%/console.log"
                level: debug
                channels: [ 'console' ]
                formatter: App\Logging\CustomLineFormatter

            doctrine:
                type: stream
                path: "%kernel.logs_dir%/doctrine.log"
                level: debug
                channels: [ 'doctrine' ]
                formatter: App\Logging\CustomLineFormatter

            debug_channel:
                type: rotating_file
                path: "%kernel.logs_dir%/debug.log"
                level: debug
                channels: [ 'debug_channel' ]
                formatter: App\Logging\CustomLineFormatter

            event:
                type: rotating_file
                path: "%kernel.logs_dir%/event.log"
                level: info
                channels: [ 'event' ]
                max_files: 30
                formatter: App\Logging\CustomLineFormatter

            profiler:
                type: rotating_file
                path: "%kernel.logs_dir%/profiler.log"
                level: info
                channels: [ 'profiler' ]
                max_files: 30
                formatter: App\Logging\CustomLineFormatter

            router:
                type: rotating_file
                path: "%kernel.logs_dir%/router.log"
                level: info
                channels: [ 'router' ]
                max_files: 30
                formatter: App\Logging\CustomLineFormatter

            http_client:
                type: fingers_crossed
                action_level: error
                buffer_size: 50
                handler: http_client_nested
                channels: [ 'http_client' ]

            http_client_nested:
                type: rotating_file
                path: "%kernel.logs_dir%/http_client.log"
                level: debug
                max_files: 30
                formatter: App\Logging\CustomLineFormatter

#            console:
#                type: console
#                process_psr_3_messages: false
#                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 30

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!deprecation"]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
